data buffer transfer
shelwinXu/eip pull request #3
Opened 2020-10-15 03:31 UTC by shelwinXu

add version1

2020-10-16 01:02 UTC, Dan-shi requested changes

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/Application.java
> +        });
PR1: should partition the list by times. it seems that times don't work here and the same list is added to the data buffer.

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/common/buffer/DataBuffer.java
> +            }
PR2: should check buffer status first

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/common/buffer/DataBuffer.java
> +            while (buffer.isEmpty()){
Since you are using ConcurrentLinkedQueue, does 'synchronized' should be used here?

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/common/buffer/DataBuffer.java
> +                if (status != DataBufferStatus.Active) {
Since you are using ConcurrentLinkedQueue, does 'synchronized' should be used here?

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/data_transfer/DataLoader.java
> +            outputStream.close();
Try to use 'try with' here

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/data_transfer/DataSender.java
> +        fip.close();
Same comment above

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/data_transfer/DataSender.java
> +    MultipleDataSources dataSources = new MultipleDataSources();
PR2: Could data source be injected to data sender?

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/data_transfer/DataSender.java
> +        reader.close();
PR1: In my perspective, the send data method should load data from the data buffer and save it to the file.

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/Application.java
> +                sourceList = dataSender.sendData(sourcePath, 10);
sendData should send buffer data to destination  file.

2020-10-16 01:02 UTC, Dan-shi commented on data_buffer_transfer/src/main/java/com/kingland/eip/Application.java
> +        List sourceList = new ArrayList<>();
The main process should be create data source, load data and send data to the destination file

2020-10-19 07:51 UTC, shelwinXu commented
@Dan-so I have solved some questions and still try to solve the rest questions. Really hope for your review. Thanks.

2020-10-19 08:22 UTC, shelwinXu commented on data_buffer_transfer/src/main/java/com/kingland/eip/Application.java
> +        });
I really uncertainty how 'times' works, it seems that the times define the thread run times. And the DataList has changed between every time thread runs.

2020-11-02 01:35 UTC, Dan-shi requested changes

2020-11-02 01:35 UTC, Dan-shi commented on data_buffer_transfer/src/test/java/com/kingland/eip/datasource/ReadFileSourceTest.java
> +    }
Normally, we should also assert exception class type is equal.

2020-11-06 00:18 UTC, merged